# External paths

export OPTION_MANAGER_DIR=../Option_Manager
export XCSP3_PARSER_DIR=../XCSP3-Parser
export XCSP3_PARSER_IDIR=$(XCSP3_PARSER_DIR)/include
export XCSP3_PARSER_LDIR=$(XCSP3_PARSER_DIR)/lib
export XML_IO_DIR=../xml_io

# Internal paths
export CORE_DIR=core
export CYCLE_CUTSET_DIR=cycle_cutset
export GRAPH_TOOLS_DIR=graph_tools
export HEURISTICS_DIR=heuristics
export IO_DIR=io
export PARTIAL_TREE_DECOMPOSITION_DIR=partial_tree-decomposition
export RANDOM_GENERATION_DIR=random_generation
export STATISTICAL_TOOL_DIR=statistical_tools
export TREE_DECOMPOSITION_DIR=tree-decomposition
export TRIANGULATION_DIR=triangulation
export VISUALIZATION_DIR=visualization_tool


# Compiler configuration
export CC = g++ 

FLAGS = -Wfatal-errors -Wall -std=c++11 -Werror -O3 -DNDEBUG #-pg 


export FLAGS_OBJ = $(FLAGS) -c
