# External paths

export GRAPH_DIR=../Graph
export GRAPH_CORE_DIR=$(GRAPH_DIR)/core
export GRAPH_TOOLS_DIR=$(GRAPH_DIR)/graph_tools
export GRAPH_TREE_DECOMPOSITION_DIR=$(GRAPH_DIR)/tree-decomposition
export XCSP3_PARSER_DIR=../XCSP3-Parser
export XCSP3_PARSER_IDIR=$(XCSP3_PARSER_DIR)/include
export XCSP3_PARSER_LDIR=$(XCSP3_PARSER_DIR)/lib
export XML_IO_DIR=../xml_io

# Internal paths
export CSP_CORE_DIR=core
export CSP_COUNTERS_DIR=statistical_information
export CSP_DECOMPOSITION_DIR=decomposition
export CSP_FILTERING_DIR=filtering
export CSP_HEURISTICS_DIR=heuristics
export CSP_IO_DIR=io
export CSP_OPTIMIZER_DIR=optimizer
export CSP_RESTART_DIR=restart
export CSP_REWRITING_RULES_DIR=rewriting_rules
export CSP_SOLVER_DIR=solver
export CSP_TOOLS_DIR=tools


# Compiler configuration
export CC = g++ 

export COMMON_LIBS = -lgraph -lparserxcsp3core `xml2-config --libs`
export COMMON_STATIC_LIBS = -lgraph -lparserxcsp3core `pkg-config --libs --static libxml-2.0` -lpthread -ldl

FLAGS = -Wfatal-errors -Wall -std=c++11 -O3 -DNDEBUG #-pg -Werror


export FLAGS_OBJ = $(FLAGS) -c
