# External paths

export OPTION_MANAGER_DIR=../Option_Manager
export XCSP3_PARSER_DIR=../XCSP3-Parser
export XCSP3_PARSER_IDIR=$(XCSP3_PARSER_DIR)/include
export XCSP3_PARSER_LDIR=$(XCSP3_PARSER_DIR)/lib
export XML_IO_DIR=../xml_io

# Internal paths
export CORE_DIR=core
export CYCLE_CUTSET_DIR=cycle_cutset
export GRAPH_TOOLS_DIR=graph_tools
export HEURISTICS_DIR=heuristics
export IO_DIR=io
export RANDOM_GENERATION_DIR=random_generation
export STATISTICAL_TOOL_DIR=statistical_tools
export TREE_DECOMPOSITION_DIR=tree-decomposition
export TRIANGULATION_DIR=triangulation
export VISUALIZATION_DIR=visualization_tool


# Compiler configuration
export CC = g++ 

export COMMON_LIBS = -loption_manager -lxml_io -lparserxcsp3core `xml2-config --libs`
export COMMON_STATIC_LIBS = -loption_manager -lxml_io -lparserxcsp3core `pkg-config --libs --static libxml-2.0` -lpthread -ldl

FLAGS = -Wfatal-errors -Wall -std=c++11 -Werror -g3 -O3 -DNDEBUG #-pg 


export FLAGS_OBJ = $(FLAGS) -c
